name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main    # ✅ only main (remove master if unused)
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          path: src
          fetch-depth: 0   # fetch all history so amend/force push works

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/src/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp **/build/*.cs3 $GITHUB_WORKSPACE/artifacts || true
          cp build/plugins.json $GITHUB_WORKSPACE/artifacts || true

      - name: Commit & Push builds to main
        run: |
          cd $GITHUB_WORKSPACE/src
          cp $GITHUB_WORKSPACE/artifacts/* .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.cs3 plugins.json || true
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force origin main
